name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Hello Git Hub Action
        run: echo "Hello this is first work flow in github action"

      - name: Bye Git Hub Action
        run: echo "Bye github changes"
